In [1]:
import torch
from torch.autograd import Variable
import torch.nn.functional as F
from torch.utils import data
from torch import nn 
import copy

from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from time import time
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, roc_curve, confusion_matrix, precision_score, recall_score, auc
from sklearn.model_selection import KFold
torch.manual_seed(2)    # reproducible torch:2 np:3
np.random.seed(3)

from config import BIN_config_DBPE
from models import BIN_Interaction_Flat
from stream import BIN_Data_Encoder

use_cuda = torch.cuda.is_available()
device = torch.device("cuda:0" if use_cuda else "cpu")

In [2]:
def test(data_generator, model):
    y_pred = []
    y_label = []
    model.eval()
    loss_accumulate = 0.0
    count = 0.0
    for i, (d, p, d_mask, p_mask, label) in enumerate(data_generator):
        score, _ = model(d.long().cuda(), p.long().cuda(), d_mask.long().cuda(), p_mask.long().cuda())
        
        m = torch.nn.Sigmoid()
        logits = torch.squeeze(m(score))
        loss_fct = torch.nn.BCELoss()            
        
        label = Variable(torch.from_numpy(np.array(label)).float()).cuda()

        loss = loss_fct(logits, label)
        
        loss_accumulate += loss
        count += 1
        
        logits = logits.detach().cpu().numpy()
        
        label_ids = label.to('cpu').numpy()
        y_label = y_label + label_ids.flatten().tolist()
        y_pred = y_pred + logits.flatten().tolist()
        
    loss = loss_accumulate/count
    
    fpr, tpr, thresholds = roc_curve(y_label, y_pred)

    precision = tpr / (tpr + fpr)

    f1 = 2 * precision * tpr / (tpr + precision + 0.00001)

    thred_optim = thresholds[5:][np.argmax(f1[5:])]

    print("optimal threshold: " + str(thred_optim))

    y_pred_s = [1 if i else 0 for i in (y_pred >= thred_optim)]

    auc_k = auc(fpr, tpr)
    print("AUROC:" + str(auc_k))
    print("AUPRC: "+ str(average_precision_score(y_label, y_pred)))

    cm1 = confusion_matrix(y_label, y_pred_s)
    print('Confusion Matrix : \n', cm1)
    print('Recall : ', recall_score(y_label, y_pred_s))
    print('Precision : ', precision_score(y_label, y_pred_s))

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)

    outputs = np.asarray([1 if i else 0 for i in (np.asarray(y_pred) >= 0.5)])
    return roc_auc_score(y_label, y_pred), average_precision_score(y_label, y_pred), f1_score(y_label, outputs), y_pred, loss.item()


def main(fold_n, lr):
    config = BIN_config_DBPE()
    
    lr = lr
    BATCH_SIZE = config['batch_size']
    train_epoch = 100
    
    loss_history = []
    
    model = BIN_Interaction_Flat(**config)
    
    model = model.cuda()

    if torch.cuda.device_count() > 1:
        print("Let's use", torch.cuda.device_count(), "GPUs!")
        model = nn.DataParallel(model, dim = 0)
            
    opt = torch.optim.Adam(model.parameters(), lr = lr)
    #opt = torch.optim.SGD(model.parameters(), lr = lr, momentum=0.9)
    
    print('--- Data Preparation ---')
    
    params = {'batch_size': BATCH_SIZE,
              'shuffle': True,
              'num_workers': 6, 
              'drop_last': True}

    dataFolder = './dataset/BindingDB'
    df_train = pd.read_csv(dataFolder + '/train.csv')
    df_val = pd.read_csv(dataFolder + '/val.csv')
    df_test = pd.read_csv(dataFolder + '/test.csv')
    
    training_set = BIN_Data_Encoder(df_train.index.values, df_train.Label.values, df_train)
    training_generator = data.DataLoader(training_set, **params)

    validation_set = BIN_Data_Encoder(df_val.index.values, df_val.Label.values, df_val)
    validation_generator = data.DataLoader(validation_set, **params)
    
    testing_set = BIN_Data_Encoder(df_test.index.values, df_test.Label.values, df_test)
    testing_generator = data.DataLoader(testing_set, **params)
    
    # early stopping
    max_auc = 0
    model_max = copy.deepcopy(model)
    
    print('--- Go for Training ---')
    torch.backends.cudnn.benchmark = True
    for epo in range(train_epoch):
        model.train()
        for i, (d, p, d_mask, p_mask, label) in enumerate(training_generator):
            score, _ = model(d.long().cuda(), p.long().cuda(), d_mask.long().cuda(), p_mask.long().cuda())

            label = Variable(torch.from_numpy(np.array(label)).float()).cuda()
            
            loss_fct = torch.nn.BCELoss()
            m = torch.nn.Sigmoid()
            n = torch.squeeze(m(score))
            
            loss = loss_fct(n, label)
            loss_history.append(loss)
            
            opt.zero_grad()
            loss.backward()
            opt.step()
            
            if (i % 100 == 0):
                print('Training at Epoch ' + str(epo + 1) + ' iteration ' + str(i) + ' with loss ' + str(loss.cpu().detach().numpy()))
            
        # every epoch test
        with torch.set_grad_enabled(False):
            auc, auprc, f1, logits, loss = test(validation_generator, model)
            if auc > max_auc:
                model_max = copy.deepcopy(model)
                max_auc = auc
            
            print('Validation at Epoch '+ str(epo + 1) + ' , AUROC: '+ str(auc) + ' , AUPRC: ' + str(auprc) + ' , F1: '+str(f1))
    
    print('--- Go for Testing ---')
    try:
        with torch.set_grad_enabled(False):
            auc, auprc, f1, logits, loss = test(testing_generator, model_max)
            print('Testing AUROC: ' + str(auc) + ' , AUPRC: ' + str(auprc) + ' , F1: '+str(f1) + ' , Test loss: '+str(loss))
    except:
        print('testing failed')
    return model_max, loss_history

In [ ]:
# fold 1
#biosnap interaction times 1e-6, flat, batch size 64, len 205, channel 3, epoch 50
s = time()
model_max, loss_history = main(1, 5e-6)
e = time()
print(e-s)
lh = list(filter(lambda x: x < 1, loss_history))
plt.plot(lh)

Let's use 8 GPUs!
--- Data Preparation ---
--- Go for Training ---


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py:30: UserWarning: 
    There is an imbalance between your GPUs. You may want to exclude GPU 0 which
    has less than 75% of the memory or cores of GPU 1. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))


Training at Epoch 1 iteration 0 with loss 0.67082864
Training at Epoch 1 iteration 100 with loss 0.6956154
Training at Epoch 1 iteration 200 with loss 0.6720772
Training at Epoch 1 iteration 300 with loss 0.70531034
Training at Epoch 1 iteration 400 with loss 0.6877631
Training at Epoch 1 iteration 500 with loss 0.71080685
Training at Epoch 1 iteration 600 with loss 0.6649274
Training at Epoch 1 iteration 700 with loss 0.69906
optimal threshold: 0.023896418511867523
AUROC:0.5510503926924208
AUPRC: 0.1653136126373162
Confusion Matrix : 
 [[   2 5712]
 [   0  926]]
Recall :  1.0
Precision :  0.13949984935221452
Accuracy :  0.13975903614457832
Sensitivity :  0.00035001750087504374
Specificity :  1.0
Validation at Epoch 1 , AUROC: 0.5510503926924208 , AUPRC: 0.1653136126373162 , F1: 0.2431283649759139


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 2 iteration 0 with loss 0.70074856
Training at Epoch 2 iteration 100 with loss 0.7485028
Training at Epoch 2 iteration 200 with loss 0.7008172
Training at Epoch 2 iteration 300 with loss 0.6781282
Training at Epoch 2 iteration 400 with loss 0.69029725
Training at Epoch 2 iteration 500 with loss 0.71803224
Training at Epoch 2 iteration 600 with loss 0.66221803
Training at Epoch 2 iteration 700 with loss 0.7087128
optimal threshold: 1.599509715788372e-07
AUROC:0.5901429250728195
AUPRC: 0.1913381390805916
Confusion Matrix : 
 [[   5 5709]
 [   0  926]]
Recall :  1.0
Precision :  0.13956292388847025
Accuracy :  0.140210843373494
Sensitivity :  0.0008750437521876093
Specificity :  1.0
Validation at Epoch 2 , AUROC: 0.5901429250728195 , AUPRC: 0.1913381390805916 , F1: 0.271850170261067


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 3 iteration 0 with loss 0.66540575
Training at Epoch 3 iteration 100 with loss 0.645267
Training at Epoch 3 iteration 200 with loss 0.702851
Training at Epoch 3 iteration 300 with loss 0.723397
Training at Epoch 3 iteration 400 with loss 0.66239595
Training at Epoch 3 iteration 500 with loss 0.6647064
Training at Epoch 3 iteration 600 with loss 0.71688735
Training at Epoch 3 iteration 700 with loss 0.685277
optimal threshold: 0.2701781988143921
AUROC:0.6047703235924954
AUPRC: 0.1947091716735116
Confusion Matrix : 
 [[   5 5708]
 [   0  927]]
Recall :  1.0
Precision :  0.13971363978899773
Accuracy :  0.14036144578313253
Sensitivity :  0.000875196919306844
Specificity :  1.0
Validation at Epoch 3 , AUROC: 0.6047703235924954 , AUPRC: 0.1947091716735116 , F1: 0.2734746862829944


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 4 iteration 0 with loss 0.6922455
Training at Epoch 4 iteration 100 with loss 0.7192669
Training at Epoch 4 iteration 200 with loss 0.70739055
Training at Epoch 4 iteration 300 with loss 0.6987235
Training at Epoch 4 iteration 400 with loss 0.69335544
Training at Epoch 4 iteration 500 with loss 0.73293394
Training at Epoch 4 iteration 600 with loss 0.7189281
Training at Epoch 4 iteration 700 with loss 0.692433
optimal threshold: 0.36540487408638
AUROC:0.6100359286153548
AUPRC: 0.20227591514058846
Confusion Matrix : 
 [[   1 5715]
 [   0  924]]
Recall :  1.0
Precision :  0.13917758698599186
Accuracy :  0.13930722891566266
Sensitivity :  0.0001749475157452764
Specificity :  1.0
Validation at Epoch 4 , AUROC: 0.6100359286153548 , AUPRC: 0.20227591514058846 , F1: 0.27643115007735947


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 5 iteration 0 with loss 0.6752542
Training at Epoch 5 iteration 100 with loss 0.68190444
Training at Epoch 5 iteration 200 with loss 0.68989444
Training at Epoch 5 iteration 300 with loss 0.6691129
Training at Epoch 5 iteration 400 with loss 0.6431672
Training at Epoch 5 iteration 500 with loss 0.70266503
Training at Epoch 5 iteration 600 with loss 0.66938007
Training at Epoch 5 iteration 700 with loss 0.698841
optimal threshold: 0.41136613488197327
AUROC:0.638869109627336
AUPRC: 0.22347223014133727
Confusion Matrix : 
 [[ 104 5609]
 [   7  920]]
Recall :  0.9924487594390508
Precision :  0.14090978710369123
Accuracy :  0.15421686746987953
Sensitivity :  0.018204095921582356
Specificity :  0.9924487594390508
Validation at Epoch 5 , AUROC: 0.638869109627336 , AUPRC: 0.22347223014133727 , F1: 0.29891614375356534


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 6 iteration 0 with loss 0.716179
Training at Epoch 6 iteration 100 with loss 0.67588747
Training at Epoch 6 iteration 200 with loss 0.71410525
Training at Epoch 6 iteration 300 with loss 0.6533613
Training at Epoch 6 iteration 400 with loss 0.6976521
Training at Epoch 6 iteration 500 with loss 0.7149603
Training at Epoch 6 iteration 600 with loss 0.66118205
Training at Epoch 6 iteration 700 with loss 0.6810506
optimal threshold: 0.4329829514026642
AUROC:0.6507373274412849
AUPRC: 0.241899031616086
Confusion Matrix : 
 [[ 512 5201]
 [  28  899]]
Recall :  0.9697950377562028
Precision :  0.14737704918032787
Accuracy :  0.2125
Sensitivity :  0.08962016453702083
Specificity :  0.9697950377562028
Validation at Epoch 6 , AUROC: 0.6507373274412849 , AUPRC: 0.241899031616086 , F1: 0.2972169683869224


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 7 iteration 0 with loss 0.67863035
Training at Epoch 7 iteration 100 with loss 0.7075503
Training at Epoch 7 iteration 200 with loss 0.7164451
Training at Epoch 7 iteration 300 with loss 0.69547665
Training at Epoch 7 iteration 400 with loss 0.6892799
Training at Epoch 7 iteration 500 with loss 0.6856911
Training at Epoch 7 iteration 600 with loss 0.64044017
Training at Epoch 7 iteration 700 with loss 0.6905979
optimal threshold: 0.45208635926246643
AUROC:0.6539385466368552
AUPRC: 0.23191907481532836
Confusion Matrix : 
 [[1457 4256]
 [ 102  825]]
Recall :  0.889967637540453
Precision :  0.16236961228104704
Accuracy :  0.3436746987951807
Sensitivity :  0.2550323822860144
Specificity :  0.889967637540453
Validation at Epoch 7 , AUROC: 0.6539385466368552 , AUPRC: 0.23191907481532836 , F1: 0.3031969749054658


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 8 iteration 0 with loss 0.6966576
Training at Epoch 8 iteration 100 with loss 0.6684482
Training at Epoch 8 iteration 200 with loss 0.6436081
Training at Epoch 8 iteration 300 with loss 0.68035567
Training at Epoch 8 iteration 400 with loss 0.6669047
Training at Epoch 8 iteration 500 with loss 0.7345364
Training at Epoch 8 iteration 600 with loss 0.6427139
Training at Epoch 8 iteration 700 with loss 0.692476
optimal threshold: 0.41647475957870483
AUROC:0.660369438558321
AUPRC: 0.23159068316790443
Confusion Matrix : 
 [[ 475 5239]
 [  25  901]]
Recall :  0.9730021598272138
Precision :  0.14674267100977198
Accuracy :  0.20722891566265061
Sensitivity :  0.08312915645782289
Specificity :  0.9730021598272138
Validation at Epoch 8 , AUROC: 0.660369438558321 , AUPRC: 0.23159068316790443 , F1: 0.3132969034608379


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 9 iteration 0 with loss 0.7125558
Training at Epoch 9 iteration 100 with loss 0.7128663
Training at Epoch 9 iteration 200 with loss 0.7055732
Training at Epoch 9 iteration 300 with loss 0.7000172
Training at Epoch 9 iteration 400 with loss 0.64543664
Training at Epoch 9 iteration 500 with loss 0.66567737
Training at Epoch 9 iteration 600 with loss 0.69183517
Training at Epoch 9 iteration 700 with loss 0.6925403
optimal threshold: 0.42990151047706604
AUROC:0.6678163821798002
AUPRC: 0.2393010167345956
Confusion Matrix : 
 [[ 865 4849]
 [  41  885]]
Recall :  0.9557235421166307
Precision :  0.15434251831182422
Accuracy :  0.2635542168674699
Sensitivity :  0.15138256912845643
Specificity :  0.9557235421166307
Validation at Epoch 9 , AUROC: 0.6678163821798002 , AUPRC: 0.2393010167345956 , F1: 0.3140852671343767


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 10 iteration 0 with loss 0.68975365
Training at Epoch 10 iteration 100 with loss 0.6623453
Training at Epoch 10 iteration 200 with loss 0.6819395
Training at Epoch 10 iteration 300 with loss 0.6860743
Training at Epoch 10 iteration 400 with loss 0.68415076
Training at Epoch 10 iteration 500 with loss 0.65957004
Training at Epoch 10 iteration 600 with loss 0.65134656
Training at Epoch 10 iteration 700 with loss 0.70105183
optimal threshold: 0.41309136152267456
AUROC:0.6436943742435502
AUPRC: 0.21621200012687863
Confusion Matrix : 
 [[ 483 5231]
 [  36  890]]
Recall :  0.9611231101511879
Precision :  0.14540107825518706
Accuracy :  0.20677710843373495
Sensitivity :  0.08452922646132306
Specificity :  0.9611231101511879
Validation at Epoch 10 , AUROC: 0.6436943742435502 , AUPRC: 0.21621200012687863 , F1: 0.30867518493611296


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 11 iteration 0 with loss 0.6984581
Training at Epoch 11 iteration 100 with loss 0.67226624
Training at Epoch 11 iteration 200 with loss 0.7055243
Training at Epoch 11 iteration 300 with loss 0.71340775
Training at Epoch 11 iteration 400 with loss 0.6939343
Training at Epoch 11 iteration 500 with loss 0.69178313
Training at Epoch 11 iteration 600 with loss 0.659202
Training at Epoch 11 iteration 700 with loss 0.65532136
optimal threshold: 0.4321930706501007
AUROC:0.6718560084864834
AUPRC: 0.25028972017764123
Confusion Matrix : 
 [[1232 4481]
 [  75  852]]
Recall :  0.919093851132686
Precision :  0.15975998499906244
Accuracy :  0.31385542168674696
Sensitivity :  0.21564852091720638
Specificity :  0.919093851132686
Validation at Epoch 11 , AUROC: 0.6718560084864834 , AUPRC: 0.25028972017764123 , F1: 0.31711026615969584


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 12 iteration 0 with loss 0.7065583
Training at Epoch 12 iteration 100 with loss 0.6967116
Training at Epoch 12 iteration 200 with loss 0.65205234
Training at Epoch 12 iteration 300 with loss 0.6949934
Training at Epoch 12 iteration 400 with loss 0.6543015
Training at Epoch 12 iteration 500 with loss 0.6816188
Training at Epoch 12 iteration 600 with loss 0.66809785
Training at Epoch 12 iteration 700 with loss 0.6943186
optimal threshold: 0.41049739718437195
AUROC:0.6560800232236234
AUPRC: 0.24129990022032016
Confusion Matrix : 
 [[ 871 4843]
 [  59  867]]
Recall :  0.9362850971922246
Precision :  0.15183887915936953
Accuracy :  0.26174698795180723
Sensitivity :  0.15243262163108157
Specificity :  0.9362850971922246
Validation at Epoch 12 , AUROC: 0.6560800232236234 , AUPRC: 0.24129990022032016 , F1: 0.3244406196213425


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 13 iteration 0 with loss 0.6356416
Training at Epoch 13 iteration 100 with loss 0.7234758
Training at Epoch 13 iteration 200 with loss 0.6694963
Training at Epoch 13 iteration 300 with loss 0.66698277
Training at Epoch 13 iteration 400 with loss 0.7128959
Training at Epoch 13 iteration 500 with loss 0.70021117
Training at Epoch 13 iteration 600 with loss 0.7132885
Training at Epoch 13 iteration 700 with loss 0.6571133
optimal threshold: 0.41791555285453796
AUROC:0.6684755944060702
AUPRC: 0.25983775703474893
Confusion Matrix : 
 [[1258 4456]
 [  88  838]]
Recall :  0.9049676025917927
Precision :  0.15829240649792217
Accuracy :  0.3156626506024096
Sensitivity :  0.2201610080504025
Specificity :  0.9049676025917927
Validation at Epoch 13 , AUROC: 0.6684755944060702 , AUPRC: 0.25983775703474893 , F1: 0.32793867120954


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 14 iteration 0 with loss 0.6447855
Training at Epoch 14 iteration 100 with loss 0.6576767
Training at Epoch 14 iteration 200 with loss 0.6982306
Training at Epoch 14 iteration 300 with loss 0.66917646
Training at Epoch 14 iteration 400 with loss 0.68461454
Training at Epoch 14 iteration 500 with loss 0.6944355
Training at Epoch 14 iteration 600 with loss 0.6945864
Training at Epoch 14 iteration 700 with loss 0.6936929
optimal threshold: 0.3922881484031677
AUROC:0.6609070778789305
AUPRC: 0.2487555278160542
Confusion Matrix : 
 [[ 344 5369]
 [  18  909]]
Recall :  0.9805825242718447
Precision :  0.14479133482000636
Accuracy :  0.18870481927710844
Sensitivity :  0.06021354804831087
Specificity :  0.9805825242718447
Validation at Epoch 14 , AUROC: 0.6609070778789305 , AUPRC: 0.2487555278160542 , F1: 0.3211554800339847


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 15 iteration 0 with loss 0.6618916
Training at Epoch 15 iteration 100 with loss 0.68710864
Training at Epoch 15 iteration 200 with loss 0.65046203
Training at Epoch 15 iteration 300 with loss 0.6691471
Training at Epoch 15 iteration 400 with loss 0.6607668
Training at Epoch 15 iteration 500 with loss 0.6555334
Training at Epoch 15 iteration 600 with loss 0.68112636
Training at Epoch 15 iteration 700 with loss 0.6924441
optimal threshold: 0.4531792998313904
AUROC:0.666443477290481
AUPRC: 0.24187033913884176
Confusion Matrix : 
 [[1389 4324]
 [ 106  821]]
Recall :  0.8856526429341963
Precision :  0.15957240038872691
Accuracy :  0.3328313253012048
Sensitivity :  0.24312970418344126
Specificity :  0.8856526429341963
Validation at Epoch 15 , AUROC: 0.666443477290481 , AUPRC: 0.24187033913884176 , F1: 0.3173996175908222


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 16 iteration 0 with loss 0.6681612
Training at Epoch 16 iteration 100 with loss 0.71710265
Training at Epoch 16 iteration 200 with loss 0.6980577
Training at Epoch 16 iteration 300 with loss 0.66663194
Training at Epoch 16 iteration 400 with loss 0.6932967
Training at Epoch 16 iteration 500 with loss 0.691681
Training at Epoch 16 iteration 600 with loss 0.67497337
Training at Epoch 16 iteration 700 with loss 0.67468655
optimal threshold: 6.741058768966468e-07
AUROC:0.6280722763484783
AUPRC: 0.211388247655654
Confusion Matrix : 
 [[   1 5712]
 [   0  927]]
Recall :  1.0
Precision :  0.1396294622684139
Accuracy :  0.13975903614457832
Sensitivity :  0.00017503938386136881
Specificity :  1.0
Validation at Epoch 16 , AUROC: 0.6280722763484783 , AUPRC: 0.211388247655654 , F1: 0.2911321807027329


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 17 iteration 0 with loss 0.6779618
Training at Epoch 17 iteration 100 with loss 0.643983
Training at Epoch 17 iteration 200 with loss 0.71707773
Training at Epoch 17 iteration 300 with loss 0.6515068
Training at Epoch 17 iteration 400 with loss 0.68369913
Training at Epoch 17 iteration 500 with loss 0.6493279
Training at Epoch 17 iteration 600 with loss 0.68553936
Training at Epoch 17 iteration 700 with loss 0.6944833
optimal threshold: 0.4091344475746155
AUROC:0.6391003945445652
AUPRC: 0.2046517181666164
Confusion Matrix : 
 [[ 498 5216]
 [  36  890]]
Recall :  0.9611231101511879
Precision :  0.1457582705535539
Accuracy :  0.20903614457831327
Sensitivity :  0.08715435771788589
Specificity :  0.9611231101511879
Validation at Epoch 17 , AUROC: 0.6391003945445652 , AUPRC: 0.2046517181666164 , F1: 0.29843953185955785


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 18 iteration 0 with loss 0.71011317
Training at Epoch 18 iteration 100 with loss 0.68474543
Training at Epoch 18 iteration 200 with loss 0.70389616
Training at Epoch 18 iteration 300 with loss 0.67865527
Training at Epoch 18 iteration 400 with loss 0.67347866
Training at Epoch 18 iteration 500 with loss 0.70124555
Training at Epoch 18 iteration 600 with loss 0.6165434
Training at Epoch 18 iteration 700 with loss 0.70601296
optimal threshold: 0.4272153675556183
AUROC:0.663010728830178
AUPRC: 0.223087921473738
Confusion Matrix : 
 [[1597 4117]
 [ 115  811]]
Recall :  0.8758099352051836
Precision :  0.16456980519480519
Accuracy :  0.36265060240963853
Sensitivity :  0.27948897444872245
Specificity :  0.8758099352051836
Validation at Epoch 18 , AUROC: 0.663010728830178 , AUPRC: 0.223087921473738 , F1: 0.3343949044585987


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 19 iteration 0 with loss 0.59689057
Training at Epoch 19 iteration 100 with loss 0.69084525
Training at Epoch 19 iteration 200 with loss 0.64665055
Training at Epoch 19 iteration 300 with loss 0.677518
Training at Epoch 19 iteration 400 with loss 0.68306357
Training at Epoch 19 iteration 500 with loss 0.6279869
Training at Epoch 19 iteration 600 with loss 0.6193225
Training at Epoch 19 iteration 700 with loss 0.70763683
optimal threshold: 0.44660988450050354
AUROC:0.6769375320881934
AUPRC: 0.23125382668840816
Confusion Matrix : 
 [[2163 3550]
 [ 149  778]]
Recall :  0.8392664509169363
Precision :  0.17975970425138632
Accuracy :  0.44292168674698795
Sensitivity :  0.37861018729214074
Specificity :  0.8392664509169363
Validation at Epoch 19 , AUROC: 0.6769375320881934 , AUPRC: 0.23125382668840816 , F1: 0.33859223300970875


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 20 iteration 0 with loss 0.6900846
Training at Epoch 20 iteration 100 with loss 0.68113995
Training at Epoch 20 iteration 200 with loss 0.69660306
Training at Epoch 20 iteration 300 with loss 0.6698166
Training at Epoch 20 iteration 400 with loss 0.6619848
Training at Epoch 20 iteration 500 with loss 0.6814348
Training at Epoch 20 iteration 600 with loss 0.62046516
Training at Epoch 20 iteration 700 with loss 0.6818689
optimal threshold: 0.43212637305259705
AUROC:0.6881191926766964
AUPRC: 0.2388430719170953
Confusion Matrix : 
 [[1606 4108]
 [  96  830]]
Recall :  0.896328293736501
Precision :  0.16808424463345484
Accuracy :  0.36686746987951807
Sensitivity :  0.28106405320266015
Specificity :  0.896328293736501
Validation at Epoch 20 , AUROC: 0.6881191926766964 , AUPRC: 0.2388430719170953 , F1: 0.33740967204002226


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 21 iteration 0 with loss 0.75223774
Training at Epoch 21 iteration 100 with loss 0.66381216
Training at Epoch 21 iteration 200 with loss 0.6709374
Training at Epoch 21 iteration 300 with loss 0.67508656
Training at Epoch 21 iteration 400 with loss 0.69984704
Training at Epoch 21 iteration 500 with loss 0.62971663
Training at Epoch 21 iteration 600 with loss 0.6549392
Training at Epoch 21 iteration 700 with loss 0.6742382
optimal threshold: 0.4246612787246704
AUROC:0.6786043715283618
AUPRC: 0.2315981070068104
Confusion Matrix : 
 [[2505 3208]
 [ 182  745]]
Recall :  0.8036677454153183
Precision :  0.18846445737414622
Accuracy :  0.4894578313253012
Sensitivity :  0.43847365657272885
Specificity :  0.8036677454153183
Validation at Epoch 21 , AUROC: 0.6786043715283618 , AUPRC: 0.2315981070068104 , F1: 0.34311670160726765


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 22 iteration 0 with loss 0.6819358
Training at Epoch 22 iteration 100 with loss 0.7194526
Training at Epoch 22 iteration 200 with loss 0.6663133
Training at Epoch 22 iteration 300 with loss 0.7027067
Training at Epoch 22 iteration 400 with loss 0.60896266
Training at Epoch 22 iteration 500 with loss 0.6740273
Training at Epoch 22 iteration 600 with loss 0.7122619
Training at Epoch 22 iteration 700 with loss 0.67192084
optimal threshold: 0.3896405100822449
AUROC:0.6517011769935183
AUPRC: 0.19534847982211093
Confusion Matrix : 
 [[1138 4575]
 [  67  860]]
Recall :  0.9277238403451996
Precision :  0.15823367065317387
Accuracy :  0.3009036144578313
Sensitivity :  0.1991948188342377
Specificity :  0.9277238403451996
Validation at Epoch 22 , AUROC: 0.6517011769935183 , AUPRC: 0.19534847982211093 , F1: 0.3148965049202579


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 23 iteration 0 with loss 0.668189
Training at Epoch 23 iteration 100 with loss 0.6526967
Training at Epoch 23 iteration 200 with loss 0.690978
Training at Epoch 23 iteration 300 with loss 0.7117002
Training at Epoch 23 iteration 400 with loss 0.65555227
Training at Epoch 23 iteration 500 with loss 0.6775181
Training at Epoch 23 iteration 600 with loss 0.65972304
Training at Epoch 23 iteration 700 with loss 0.6382162
optimal threshold: 0.42399075627326965
AUROC:0.646658088843967
AUPRC: 0.20183212796506594
Confusion Matrix : 
 [[1352 4362]
 [  87  839]]
Recall :  0.906047516198704
Precision :  0.16131513170544126
Accuracy :  0.3299698795180723
Sensitivity :  0.23661183059152957
Specificity :  0.906047516198704
Validation at Epoch 23 , AUROC: 0.646658088843967 , AUPRC: 0.20183212796506594 , F1: 0.30818791946308727


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 24 iteration 0 with loss 0.68990356
Training at Epoch 24 iteration 100 with loss 0.7046473
Training at Epoch 24 iteration 200 with loss 0.7651698
Training at Epoch 24 iteration 300 with loss 0.6845608
Training at Epoch 24 iteration 400 with loss 0.6877582
Training at Epoch 24 iteration 500 with loss 0.6195511
Training at Epoch 24 iteration 600 with loss 0.6992395
Training at Epoch 24 iteration 700 with loss 0.6584714
optimal threshold: 0.39975234866142273
AUROC:0.6710561585207255
AUPRC: 0.25076450096947317
Confusion Matrix : 
 [[1771 3944]
 [ 124  801]]
Recall :  0.865945945945946
Precision :  0.16880927291886197
Accuracy :  0.38734939759036147
Sensitivity :  0.30988626421697285
Specificity :  0.865945945945946
Validation at Epoch 24 , AUROC: 0.6710561585207255 , AUPRC: 0.25076450096947317 , F1: 0.3278563240351548


/home/ken/miniconda3/envs/MolTrans/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in true_divide


Training at Epoch 25 iteration 0 with loss 0.63341814
Training at Epoch 25 iteration 100 with loss 0.68980896
Training at Epoch 25 iteration 200 with loss 0.65841216
Training at Epoch 25 iteration 300 with loss 0.7085751
Training at Epoch 25 iteration 400 with loss 0.71747935
Training at Epoch 25 iteration 500 with loss 0.6988963
Training at Epoch 25 iteration 600 with loss 0.7091571
Training at Epoch 25 iteration 700 with loss 0.6682226
